import { StyleSheet } from 'react-native';

import type { Palette } from '@/src/design-system';

export const createStyles = (palette: Palette) => StyleSheet.create({
  root: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  actionsColumn: {
    position: 'absolute',
    right: 16,
    bottom: 28,
    alignItems: 'flex-end',
    gap: 8,
    zIndex: 15,
  },
  actionButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.mapControlSurface,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 8,
  },
  actionButtonIdle: {
    opacity: 0.82,
  },
  locationMessage: {
    position: 'absolute',
    right: 16,
    bottom: 80,
    maxWidth: 240,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: palette.surfaceTranslucent,
    borderWidth: 1,
    borderColor: palette.border,
    zIndex: 15,
  },
  locationMessageText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  transferBadgeRow: {
    flexDirection: 'row',
    gap: 2,
  },
  transferBadgeAnchorBox: {
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    minWidth: 34,
    minHeight: 23,
    paddingLeft: 26,
    paddingBottom: 11,
  },
  transferBadge: {
    minWidth: 24,
    height: 19,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: palette.surface,
  },
  transferBadgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  extraBadge: {
    minWidth: 21,
    height: 19,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    backgroundColor: palette.surfaceElevated,
    borderWidth: 1,
    borderColor: palette.surface,
  },
  extraBadgeText: {
    color: palette.text,
    fontSize: 10,
    fontWeight: '900',
  },
  nearbyDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOpacity: 0.32,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 3,
  },
  selectedStationHitTarget: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedStationHalo: {
    width: 29,
    height: 29,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedStationCore: {
    width: 21,
    height: 21,
    borderRadius: 11,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  // Sized to fit the sonar rings so the rasterised bitmap is never clipped.
  vehicleMarkerBox: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehiclePulseRing: {
    position: 'absolute',
    top: 3,
    left: 3,
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  // Rotated around the box centre so the tip circles the marker edge,
  // pointing along the vehicle heading; the train glyph itself stays upright.
  vehicleHeadingBox: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 60,
    height: 60,
    alignItems: 'center',
  },
  vehicleHeadingTip: {
    marginTop: 8,
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FFFFFF',
  },
  // Centred in the 60 pt marker box, behind the tile.
  vehicleSelectedHalo: {
    position: 'absolute',
    top: 10.5,
    left: 10.5,
    width: 39,
    height: 39,
    borderRadius: 15,
    borderWidth: 1.5,
  },
  // A rounded tile, deliberately not a circle: every station annotation on the
  // map is a white-ringed disc, and a disc-shaped vehicle at a station read as
  // a second station rather than as a train. The radius stays close to circular
  // so the orbiting heading tip keeps an even gap at every angle — a squarer
  // corner reaches further from the centre than the middle of an edge does.
  vehicleMarker: {
    width: 27,
    height: 27,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
    shadowColor: palette.shadow,
    shadowOpacity: 0.32,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  // Lives inside a Marker, so it sizes to its content and needs no positioning
  // of its own. The cap keeps a long destination from spanning the viewport.
  vehicleCard: {
    // Fits "Barcelona - Plaça Catalunya", the longest destination on the network.
    maxWidth: 248,
    gap: 3,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: palette.surfaceElevated,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 8,
  },
  vehicleCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  vehicleCardBadge: {
    minWidth: 26,
    height: 19,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  vehicleCardBadgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  vehicleCardDestination: {
    flexShrink: 1,
    color: palette.text,
    fontSize: 13,
    fontWeight: '800',
  },
  vehicleCardMeta: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
  },
  nearbyLabel: {
    maxWidth: 140,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 6,
    backgroundColor: palette.surfaceTranslucent,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: palette.borderStrong,
    paddingLeft: 3,
    paddingRight: 6,
    paddingVertical: 2,
    gap: 4,
  },
  nearbyLabelBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nearbyLabelBadgeText: {
    color: palette.textInverse,
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  nearbyLabelText: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.1,
    flexShrink: 1,
  },
  plannerMarker: {
    minWidth: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    backgroundColor: palette.surfaceStrong,
    borderWidth: 2,
    borderColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 6,
  },
  plannerEndpointWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  plannerMarkerSelected: {
    borderColor: palette.accent,
    borderWidth: 4,
  },
  destinationTail: {
    width: 10,
    height: 10,
    marginTop: -7,
    transform: [{ rotate: '45deg' }],
    backgroundColor: palette.surfaceStrong,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: palette.surface,
  },
  plannerMarkerText: {
    color: palette.textInverse,
    fontSize: 13,
    fontWeight: '800',
  },
  // An opaque fill and a real 1 pt outline: over a map the translucent surface
  // let the streets underneath through, and a hairline in a surface tone had
  // nothing to separate the label from whatever it happened to sit on.
  stationNameLabel: {
    maxWidth: 156,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 7,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.textMuted,
    paddingHorizontal: 7,
    paddingVertical: 3,
    shadowColor: palette.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  stationNameLabelEmphasized: {
    backgroundColor: palette.surfaceElevated,
    borderWidth: 2.5,
    shadowOpacity: 0.4,
    shadowRadius: 6,
    transform: [{ scale: 1.04 }],
  },
  stationNameText: {
    color: palette.text,
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'left',
    letterSpacing: 0.1,
  },
  stationNameTextEmphasized: {
    fontSize: 12,
    fontWeight: '800',
    color: palette.text,
  },
});
