import { StyleSheet } from 'react-native';

import type { Palette } from '@/src/design-system';

export const createStyles = (palette: Palette) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  header: {
    gap: 12,
    paddingBottom: 14,
  },
  titleRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  titleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: palette.text,
    fontSize: 28,
    fontWeight: '800',
  },
  subtitle: {
    marginTop: 2,
    color: palette.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  summaryCompact: {
    flexShrink: 1,
    alignItems: 'flex-end',
    gap: 1,
  },
  summaryHeadline: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'nowrap',
    gap: 5,
  },
  summaryValue: {
    flexShrink: 0,
    color: palette.text,
    fontSize: 20,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  summaryLabel: {
    flexShrink: 1,
    color: palette.text,
    fontSize: 13,
    fontWeight: '800',
  },
  summaryDetail: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    textAlign: 'right',
  },
  filterStack: {
    gap: 8,
  },
  mineFilterButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.surface,
  },
  mineFilterButtonActive: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  mineFilterIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderCurve: 'continuous',
    backgroundColor: palette.warningSoft,
  },
  mineFilterIconActive: {
    backgroundColor: palette.accent,
  },
  mineFilterLabel: {
    flex: 1,
    minWidth: 0,
    color: palette.text,
    fontSize: 14,
    fontWeight: '800',
  },
  mineFilterLabelActive: {
    color: palette.accentPressed,
  },
  mineFilterCount: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  mineFilterCountActive: {
    color: palette.accentPressed,
  },
  segmentedControl: {
    flexDirection: 'row',
    gap: 4,
    padding: 4,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.divider,
  },
  segmentButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 6,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 12,
    borderCurve: 'continuous',
  },
  segmentButtonActive: {
    backgroundColor: palette.surface,
    shadowColor: palette.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  segmentButtonActiveDark: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  segmentLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  segmentLabelActive: {
    color: palette.text,
  },
  segmentCount: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  segmentCountActive: {
    color: palette.accent,
  },
  filterButtonPressed: {
    opacity: 0.72,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderCurve: 'continuous',
    backgroundColor: palette.dangerSoft,
  },
  errorText: {
    flex: 1,
    minWidth: 0,
    color: palette.danger,
    fontSize: 13,
    fontWeight: '700',
  },
  retryButton: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: palette.danger,
  },
  retryText: {
    color: palette.textInverse,
    fontSize: 12,
    fontWeight: '900',
  },
  separator: {
    height: 10,
  },
  emptyState: {
    minHeight: 230,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 24,
    borderRadius: 16,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
  },
  emptyIcon: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: palette.divider,
  },
  emptyTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyBody: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  resetFiltersButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: palette.accent,
  },
  resetFiltersButtonPressed: {
    backgroundColor: palette.accentPressed,
  },
  resetFiltersText: {
    color: palette.onAccent,
    fontSize: 14,
    fontWeight: '800',
  },
});
